Upgrade to Nushell v0.108.0
Add a '..' to ignore added fields (I have not checked what was added and whether it may be useful or should be used)
to resolve `error[E0638]: `..` required with variant marked as non-exhaustive`